### ISSUE TITLE
Requirements.txt version issue for feedparser

### ISSUE THREAD

**Issue by alex-mcd** [kirstykitto/CLAtoolkit#17]
When trying to create the docker container (or install with pip locally) an error occurs when trying to install feedparser. It appears they've renamed [version 5.2.0 to 5.2.0.post1](https://github.com/kurtmckee/feedparser/issues/22)

I managed to fix it by changing the required version to 5.2.1

The only change in 5.2.1 is to [fix the version naming](https://github.com/kurtmckee/feedparser/blob/develop/NEWS)

Example error below

```
Downloading/unpacking feedparser==5.2.0 (from -r requirements.txt (line 38))
  Could not find a version that satisfies the requirement feedparser==5.2.0 (from -r requirements.txt (line 38)) (from versions: 5.2.0.post1, 5.0.1, 5.1, 5.1.1, 5.1.2, 5.2.1, 5.1.2, 5.2.0.post1, 4.1, 5.0, 5.0, 5.0.1, 5.1.3, 5.0.1, 5.1.1, 5.2.1, 5.1.2, 5.1, 5.0, 5.1.1, 5.1.3, 5.2.1, 5.1.3, 5.2.0.post1, 5.1)
```

**Comment by zwaters** [comment]
Closed - fixed with feedparser merge. Thanks again!
