### ISSUE TITLE
iGraph Depreciated - Potential Issue

### ISSUE THREAD

**Issue by zwaters** [kirstykitto/CLAtoolkit#25]
Although there are no current conflicts - this may become an issue in the future and should be followed up.

See http://stackoverflow.com/questions/36200707/error-with-igraph-library-deprecated-library

**Comment by tommarmstrong** [comment]
A fatal error is shown when using igraph instead of python-igraph, the dep definitely needs to be updated.

```
DeprecationWarning at /
To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.
```
