### ISSUE TITLE
Check activity date when imported?

### ISSUE THREAD

**Issue by kojiagile** [kirstykitto/CLAtoolkit#77]
Unitoffering table has now the start date and end date. The activity/platform timeseries chart shows the imported data that is between the two dates. However, all data is imported if the date of the data is earlier/later than start/end date.
As data is imported, should the toolkit check the date of data and reject it if the date is not between the start date and end date of a unit?

**Comment by kirstykitto** [comment]
No - there is a possible use case where students will want to track their contributions after the class... we will need to be able to deal with that somehow.

**Comment by zwaters** [comment]
That's what I thought 😊

We decided to hold-off implementing anything until we could chat about it.. I also thought of a use case where students are actually posting into a social media platform a week or so before class starts (unlikely, but hey it might happen :P).

**Comment by kirstykitto** [comment]
Actually - it is not that unusual at all in some of the ideas that UTS is exploring right now :)
